# Generated by Django 3.1.2 on 2020-10-27 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('I', 'Toàn bộ hoá đơn'), ('P', 'Sản phẩm')], max_length=1)),
                ('beneficiary', models.IntegerField(choices=[('E', 'Mọi khách hàng'), ('N', 'Khách hàng hệ thống'), ('V', 'Khách hàng VIP')], default='E')),
                ('discount_percent', models.FloatField(blank=True)),
                ('max_discount_money', models.PositiveIntegerField(blank=True)),
                ('app_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exp_date', models.DateTimeField()),
                ('note', models.TextField(default='')),
            ],
        ),
    ]
