# Generated by Django 3.1.2 on 2020-10-25 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='app_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
