# Generated by Django 3.1.2 on 2020-10-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=10)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(default='')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Xoá'), (1, 'Hoàn thành')], default=1)),
                ('total_products', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=10)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(default='')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Xoá'), (1, 'Hoàn thành'), (2, 'Chưa xử lý')], default=2)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
