# Generated by Django 3.1.2 on 2020-10-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30)),
                ('barcode', models.CharField(default='', max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('images', models.CharField(default='', max_length=255)),
                ('cost_price', models.PositiveIntegerField()),
                ('sell_price', models.PositiveIntegerField()),
                ('available', models.FloatField()),
                ('unit', models.CharField(choices=[('GR', '100 gram'), ('KG', 'kilogram'), ('INT', 'chiếc/cái')], default='INT', max_length=3)),
                ('status', models.IntegerField(choices=[(0, 'xoá'), (1, 'đang bán'), (2, 'ngừng bán')], default=1)),
                ('mfg', models.DateField()),
                ('exp', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_object_id', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sales_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
